### PR TITLE
No more false errors when hitting remove button fixes

### LINKED ISSUE #46: You can delete a channel even when you shouldn't be able to.
This issue originates in the templates:

https://github.com/LabVIEW-DCAF/DCAF-Project-Templates/issues/103

### PR DESCRIPTION
**Pull request by theSloopJohnB**
adding case structure to "Remove Button" case that does nothing if
removing a non-channel. fixes #46

### CODE REVIEW

**Comment by pollockm** [comment]
We should be able to fix the root cause of this issue as well - make the Table API value change event set the value of the listbox to -1 if the listbox contains no items.  This would have the effect of disabling the Remove button on all modules if the listbox is empty, without needing to modify the modules themselves.

**Comment by theSloopJohnB** [comment]
Even better! I'll try it out.

**Comment by pollockm** [comment]
I don't like that this check is happening at the top-level UI VI.  For this one, I prefer to put this check down in the responsible function.  In this case, Scan Engine Configuration: Delete Line.vi.  This is dependent on an assumption that blank line name should always be ignored, which I'm not sure is a valid assumption.

I prefer the approach of disabling and greying out the remove button if there is nothing to remove, which removes the need for the assumption.

**Comment by theSloopJohnB** [comment]
Great suggestions, and thanks for the specific advice!

This issue does not even belong in the scan engine repo or template repo in that case. I'll close this PR and follow up with it in the TagEditorCore.

**Pull request closed without merging**
